export const CREATE_USER = {
	REQUESTED: 'CREATE_USER_REQUESTED',
	SUCCESS: 'CREATE_USER_SUCCESS',
	FAILURE: 'CREATE_USER_FAILURE'
};
export const UPDATE_USER = {
	REQUESTED: 'UPDATE_USER_REQUESTED',
	SUCCESS: 'UPDATE_USER_SUCCESS',
	FAILURE: 'UPDATE_USER_FAILURE'
};
export const DELETE_USER = {
	REQUESTED: 'DELETE_USER_REQUESTED',
	SUCCESS: 'DELETE_USER_SUCCESS',
	FAILURE: 'DELETE_USER_FAILURE'
};
export const FETCH_USERS = {
	REQUESTED: 'FETCH_USERS_REQUESTED',
	SUCCESS: 'FETCH_USERS_SUCCESS',
	FAILURE: 'FETCH_USERS_FAILURE'
};
